# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a60c461e4a59c80fe022602b2bdfc8b36eb8e9ea38f7875c7662d0ba85e283a71ff0c011da75da776a6f0edaf77e97d3120ab358dbbe8b8eebfd1e4d001e56

test:
  secret_key_base: 5cfe30a7d6e0de819d016d28d35e07209ce872f6577171f0b54660d10de14f0b2b2d26fad5fdc6134af4040f19d49be55428ed5034efb453e9bd21b868b0aa54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
